---

- import_tasks: raspbian.yml
  become: yes
  become_user: root
  when: ansible_lsb.id == "Raspbian"

- import_tasks: ubuntu-20.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- import_tasks: ubuntu-22.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
