---

- name: memcache
  apt: name=memcached state=present

- name: Install PHP (Ubuntu 14.04)
  apt: name="{{ item }}" state=present
  with_items:
    - php5
    - php-apc
    - php5-cgi
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mcrypt
    - php5-mysqlnd
    - php5-sqlite
    - php5-xml

- name: Download and Install Composer (Ubuntu 14.04)
  shell: "{{ item }}"
  with_items:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - cp composer.phar /usr/local/bin/composer
    - rm -f composer.phar  composer-setup.php
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Enable PHP mods (Ubuntu 14.04)
  shell: "php5enmod {{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  with_items:
    - bcmath
    - curl
    - dom
    - mbstring
    - mcrypt
    - phar
    - xml
