---

- name: memcache
  apt: name=memcached state=present

- name: Install PHP (Ubuntu 20.04)
  apt:
    pkg:
      - php
      - php-amqplib
      - php-apcu
      - php-bcmath
      - php-cgi
      - php-curl
      - php-gd
      - php-imagick
      - php-json
      - php-mysqlnd
      - php-sqlite3
      - php-xml

- name: Install Composer (Ubuntu 20.04)
  apt: name=composer state=latest

- name: Enable PHP mods (Ubuntu 20.04)
  shell: "phpenmod {{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  with_items:
    - amqplib
    - bcmath
    - curl
    - dom
    - mbstring
    - mcrypt
    - phar
    - xml
