---

- name: memcache
  apt: name=memcached state=present

- name: Install PHP (Ubuntu 16.04)
  apt:
    state: present
    name:
      - php5
      - php-apc
      - php-cgi
      - php-curl
      - php-gd
      - php-imagick
      - php-json
      - php-mcrypt
      - php-mysqlnd
      - php-sqlite
      - php-xml

- name: Install Composer (Ubuntu 16.04)
  apt: name=composer state=latest

- name: Enable PHP mods (Ubuntu 16.04)
  shell: "phpenmod {{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  with_items:
    - curl
    - mcrypt
    - bcmath
    - dom
    - mbstring
    - phar
    - xml
