---

- name: memcache
  apt: name=memcached state=present

- name: 'Install up-to-date PHP PPA'
  shell: add-apt-repository -y ppa:ondrej/php

- name: Remove PHP 7.2 and libraries
  apt:
    name:
      - php7.2
      - php7.2-bcmath
      - php7.2-cgi
      - php7.2-curl
      - php7.2-gd
      - php7.2-imagick
      - php7.2-json
      - php7.2-mbstring
      - php7.2-memcached
      - php7.2-mysql
      - php7.2-pcov
      - php7.2-sqlite3
      - php7.2-xml
      - php7.2-zip
    state: absent

- name: Install PHP 7.4 and libraries
  apt:
    name:
      - php7.4
      - php7.4-bcmath
      - php7.4-cgi
      - php7.4-curl
      - php7.4-gd
      - php7.4-imagick
      - php7.4-json
      - php7.4-mbstring
      - php7.4-memcached
      - php7.4-mysql
      - php7.4-pcov
      - php7.4-sqlite3
      - php7.4-xml
      - php7.4-zip
    state: present

- name: 'Set default PHP version (7.4)'
  alternatives:
    name: php
    priority: -10
    path: /usr/bin/php7.4

- name: Enable PHP mods
  shell: "phpenmod {{ item }}"
  with_items:
    - amqplib
    - bcmath
    - curl
    - dom
    - mbstring
    - mcrypt
    - memcached
    - phar
    - xml
    - zip

- name: Download latest Composer
  get_url:
    # if checksum ever breaks, find out the new one at:
    # curl -sS https://composer.github.io/installer.sig
    checksum: sha384:dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-setup.php'

- name: Install Composer
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
